25.select distinct group_concat(s.namefirst," ",c.name) from student s join batch_students bs on s.id=bs.studentid join course_batches cb on bs.batchid=cb.id join course c on c.id=cb.courseid group by s.namefirst having s.namefirst="ruhan";
24.select concat(s.namefirst,",",group_concat(sc.name)) from student s join student_cards sc on s.id=sc.studentid group by s.namefirst having s.namefirst="saleel";
23.select c.name,group_concat(m.name) from course c join course_modules cm on c.id=cm.courseid join modules m on cm.moduleid=m.id group by c.name having m.name="java1";
21.select s.namefirst,count(sp.number) from student s join student_phone sp on s.id=sp.studentid group by s.namefirst having count(sp.number)>2;
19.select s.*,sq.name from student s join student_qualifications sq on s.id=sq.studentid where sq.name="be";
18.select c.name,group_concat(m.name) as module, count(m.name) from course c join course_modules cm on c.id=cm.courseid join modules m on m.id=cm.moduleid group by c.name;
17.select c.name,group_concat(m.name) from course c join course_modules cm on c.id=cm.courseid join modules m on m.id=cm.moduleid group by c.name having c.name="pg-dac";
16.select c.*,cb.starton from course c join course_batches cb on c.id=cb.courseid where cb.starton="2016-02-01";
15.select distinct s.* from student s join batch_students bs on s.id=bs.studentid join course_batches cb on cb.id=bs.batchid join course c on c.id=cb.courseid where c.name="pg-dac";
14.select c.name, group_concat(cb.name) from course c join course_batches cb on c.id=cb.courseid group by c.name;
13.select f.*,fp.number,fa.address from faculty f join faculty_phone fp on f.id=fp.facultyid join faculty_address fa on f.id=fa.facultyid where f.name="ketan";
12.select s.*,sa.address,sq.* from student s join student_qualifications sq on s.id=sq.studentid join student_address sa on s.id=sa.studentid;
11.select s.namefirst,count(sp.number) from student s join student_phone sp on s.id=sp.studentid group by s.namefirst;
10.select distinct s.namefirst,s.namelast,sp.number,s.emailid from student s join student_phone sp on s.id=sp.studentid where s.id=13;
9.select s.namefirst,s.namelast,group_concat(cb.name) from student s join batch_students bs on s.id=bs.studentid join course_batches cb on cb.id=bs.batchid group by s.namefirst;
8.select c.name ,group_concat(m.name) from course c join course_modules cm on c.id=cm.courseid join modules m on m.id=cm.moduleid group by c.name having c.name="pg-dac";
7.select s.*,cb.* from student s join batch_students bs on s.id=bs.studentid join course_batches cb on cb.id=bs.batchid where cb.name="batch1";
6.select m.name,m.duration from modules m join course_modules cm on m.id=cm.moduleid join course_batches cb on cb.courseid=cm.courseid where cb.name="batch1";
5.select s.*,sq.* from student s join student_qualifications sq on s.id=sq.studentid where sq.name="be";
4.select s.*,sq.*,sp.* from student s join student_qualifications sq on s.id=sq.studentid join student_phone sp on s.id=sp.studentid;
3.select s.*,sq.* from student s join student_qualifications sq on s.id=sq.studentid where sq.university="yale university";
2.select s.namefirst,s.namelast,s.emailid,sq.* from student s join student_qualifications sq on s.id=sq.studentid;
1.select s.*,sa.* from student s join student_address sa on s.id=sa.studentid;